### PR TITLE
Don't throw an exception if Encoding doesn't have BaseEncoding

### LINKED ISSUE #432: "BaseEncoding" should be optional
In `Encoding->getEncodingClass()`, if the field `BaseEncoding` doesn't exist, it throws an Exception but, accordingly PDF 1.5 Reference Table 5.11 (attached), the field `BaseEncoding` is optional, so, if any PDF builder don't put this field, pdfparser will crash.

image

### PR DESCRIPTION
**Pull request by LucianoHanna**
Fixes #432 

`$this->get('Encoding')->__toString()` throws an exception when Encoding don't have BaseEncoding attribute, so I put it on a try catch because if Encoding don't have BaseEncoding, of course `WinAnsiEncoding::class === $this->get('Encoding')->__toString()` will return false

I didn't make any unit test because I only have a confidential PDF file which cause this bug

### CODE REVIEW

File: src/Smalot/PdfParser/Font.php [hunk 1]
```diff
@@ -107,9 +107,15 @@ public function translateChar($char, $use_default = true)
...
         ) {
-            $fallbackDecoded = self::uchr($dec);
+            try {
+                if (WinAnsiEncoding::class === $this->get('Encoding')->__toString()) {
+                    $fallbackDecoded = self::uchr($dec);
+                }
+            } catch (\Exception $e) {
+                // Encoding->getEncodingClass() throws an exception when BaseEncoding doesn't exists
+                // See table 5.11 on PDF 1.5 specs for more info
+            }
```
Comment (k00ni) [inline src/Smalot/PdfParser/Font.php:118]: I get what you want to achieve here but a "catch-all" at this point might hide other viable exceptions. 

What do you think about adapting `getEncodingClass` to throw a specific exception like `EncodingClassNotFoundException`. We could catch that and ignore the rest at this point.

**Review by k00ni — CHANGES_REQUESTED** [review]
@LucianoHanna thank you for the PR!

File: src/Smalot/PdfParser/Font.php (hunk 1 above)
Comment (LucianoHanna) [reply src/Smalot/PdfParser/Font.php]: I agree, a "catch-all" can create a new bug if any other Exception was raised.

**Comment by LucianoHanna** [comment]
Hi,

I tried to create a pdf without sensitive information but I did not make it...
So I created a test only barely reproducing the state that would cause this error.

Test with a real pdf would be a lot better... I appreciate a lot if someone could help with it!

File: src/Smalot/PdfParser/Font.php [hunk 2]
```diff
@@ -107,9 +107,15 @@ public function translateChar($char, $use_default = true)
...
             && $this->get('Encoding') instanceof Encoding
-            && WinAnsiEncoding::class === $this->get('Encoding')->__toString()
         ) {
-            $fallbackDecoded = self::uchr($dec);
+            try {
+                if (WinAnsiEncoding::class === $this->get('Encoding')->__toString()) {
+                    $fallbackDecoded = self::uchr($dec);
+                }
+            } catch (EncodingNotFoundException $e) {
+                // Encoding->getEncodingClass() throws an exception when BaseEncoding doesn't exists
```
Comment (k00ni) [inline src/Smalot/PdfParser/Font.php:116]:
```suggestion
                // Encoding->getEncodingClass() throws EncodingNotFoundException when BaseEncoding doesn't exists
```

File: src/Smalot/PdfParser/EncodingNotFoundException.php [hunk 3]
```diff
@@ -0,0 +1,7 @@
+<?php
+
+namespace Smalot\PdfParser;
+
+class EncodingNotFoundException extends \Exception
+{
+}
```
Comment (k00ni) [inline src/Smalot/PdfParser/EncodingNotFoundException.php:7]: Please move to `src/Smalot/PdfParser/Exception`.

File: tests/Integration/FontTest.php [hunk 4]
```diff
@@ -379,4 +379,17 @@ public function testXmlContent()
 
         $this->assertEquals('Example PDF', $text);
     }
+
+    /**
+     * Create a header containing a Encoding that doesn't have a BaseEncoding
+     * so I test if the Font won't raise a exception because Encoding don't have BaseEncoding
```
Comment (k00ni) [inline tests/Integration/FontTest.php:385]:
```suggestion
     * Create an instance of Header containing an instance of Encoding that doesn't have a BaseEncoding.
     * Test if the Font won't raise a exception because Encoding don't have BaseEncoding.
```

**Review by k00ni — CHANGES_REQUESTED** [review]
Nicely done!

About tests: There are different types, like integration and functional tests. Using a PDF is not the best way, because it involves a lot of code. Though, if we have PDFs available to exploit existing problems, they should be part of the tests. At this point if prefer integration tests like you did with `testEncodingWithoutBaseEncoding`. 👍🏿

**Comment by LucianoHanna** [comment]
> Nicely done!
> 
> About tests: There are different types, like integration and functional tests. Using a PDF is not the best way, because it involves a lot of code. Though, if we have PDFs available to exploit existing problems, they should be part of the test suite. At this point I prefer integration tests like you did with `testEncodingWithoutBaseEncoding`. 👍🏿

Thank you for your feedback!

**Review by k00ni — APPROVED** [review]
Looks good to me. Will leave this open for a few days.

@j0k3r @izabala any remarks?

**Review by j0k3r — APPROVED** [review]
Looks good!

**Comment by LucianoHanna** [comment]
Any news about this merge and new release?

**Comment by k00ni** [comment]
> Any news about this merge and new release?

For me its important to give the community a time window to comment/test new pull requests. Therefore I wrote that I will leave this open for a few days. 

Do you need it asap?

**Comment by LucianoHanna** [comment]
> > Any news about this merge and new release?
> 
> For me its important to give the community a time window to comment/test new pull requests. Therefore I wrote that I will leave this open for a few days.
> 
> Do you need it asap?

Sorry, I thought you would leave this open for a few days until have another approval.

It's better to give the community a time window.

Thank you
