### PR TITLE
fix missing catalog bug (+ some code refactoring)

### LINKED ISSUE #267: In Parser.php line 154: Notice: Trying to access array offset on value of type int
Hi
I have an error :
`In Parser.php line 154: Notice: Trying to access array offset on value of type int 
`

### PR DESCRIPTION
**Pull request by PaulBehrendtVentoro**
fixes #267

### CODE REVIEW

**Comment by j0k3r** [comment]
@k00ni We really have an issue with Travis not triggered from time to time 😔

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 1]
```diff
@@ -471,7 +471,7 @@ protected function getIndirectObject($pdfData, $xref, $obj_ref, $offset = 0, $de
         }
         $objref = $obj[0].' '.$obj[1].' obj';
         // ignore leading zeros
-        $offset += strspn($pdfData, '0', $offset);
+        $offset += strspn($pdfData, "0\n", $offset);
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:474]: Could you please describe how you come up with this fix?

File: tests/Integration/ParserTest.php [hunk 2]
```diff
@@ -86,12 +86,10 @@ public function testParseFile()
      *      Missing catalog.
      *
      * @see https://github.com/smalot/pdfparser/issues/267
+     * @doesNotPerformAssertions
```
Comment (k00ni) [inline tests/Integration/ParserTest.php:89]: The purpose of this test (`testIssue267`) was to keep track of a faulty functionality. After your fix this test should be altered and actually do something with the extracted data. I am open for suggestions.

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 1 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php:474]: Yes, this is more like a dirty fix. The offset given by `RawDataParser::getXrefData` is off by a newline for the given PDF which does not fit assumptions in `RawDataParser::getIndirectObject`. But i am new to this package and not so familiar with PDF-standards, so i was afraid of changing regex in `getXrefData`. To me all seamed to work fine when adding newlines to the trimming in `getIndirectObject`. But i will review `RawDataParser::getXrefData` again, so maybe wait a bit if you intend to merge.

File: tests/Integration/ParserTest.php (hunk 2 above)
Comment (PaulBehrendtVentoro) [reply tests/Integration/ParserTest.php:89]: Ok i will add some test cases.

Comment (k00ni) [reply tests/Integration/ParserTest.php:89]: Looking forward to it.

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 1 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: Ok I did not find anything on cross-ref offsets and leading newlines. So i guess it is fine to throw it away. Assuming "Microsoft: Print To PDF" has correctly implemented PDF-1.7-standard & given PDF was not corrupted afterwards.

File: tests/Integration/ParserTest.php [hunk 3]
```diff
@@ -66,7 +67,7 @@ public function testParseFile()
                     } catch (Exception $e) {
                         if (
                             'Secured pdf file are currently not supported.' !== $e->getMessage()
-                            && 0 != strpos($e->getMessage(), 'TCPDF_PARSER')
+                            && 0 !== strpos($e->getMessage(), 'TCPDF_PARSER')
```
Comment (PaulBehrendtVentoro) [inline tests/Integration/ParserTest.php:70]: please double check this. looked like a bug to me, because the "Missing catalog"-Exception was not catched by this test.

Comment (k00ni) [reply tests/Integration/ParserTest.php:70]: The `TCPPDF_PARSER` reference is obsolete there and could be removed. But it should be done separately as long as it doesn't interfere with your fix.

File: tests/Integration/ParserTest.php [hunk 4]
```diff
@@ -77,26 +78,17 @@ public function testParseFile()
...
-        $this->expectExceptionMessage('Missing catalog.');
-
         $filename = $this->rootDir.'/samples/bugs/Issue267_array_access_on_int.pdf';
 
         $document = $this->fixture->parseFile($filename);
 
-        // triggers the exception
-        $document->getPages();
+        self::assertEquals(Image::class, \get_class($document->getObjectById('128_0')));
+        self::assertStringContainsString('4 von 4', $document->getText());
```
Comment (j0k3r) [inline tests/Integration/ParserTest.php:92]: We usually use `$this->` instead of `self::`

```suggestion
        $this->assertEquals(Image::class, \get_class($document->getObjectById('128_0')));
        $this->assertStringContainsString('4 von 4', $document->getText());
```

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 1 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: I think in the tc-lib-pdf-parser project this was solved by the `$offset++` there
See https://github.com/tecnickcom/tc-lib-pdf-parser/pull/6/files

File: tests/Integration/ParserTest.php (hunk 3 above)
Comment (PaulBehrendtVentoro) [reply tests/Integration/ParserTest.php:70]: So you mean i should remove it in another PR?

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 1 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: Ok i tried this solution, works as well. Not sure which one is better.

File: tests/Integration/ParserTest.php (hunk 3 above)
Comment (k00ni) [reply tests/Integration/ParserTest.php:70]: As long as it doesn't interfere with your fix, leave it be. We can take care of it later on.

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 1 above)
Comment (k00ni) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: ### About TCPDF
There are so many repositories from tecnickcom for PDF parser: 
* **https://github.com/tecnickcom/TCPDF**
* https://github.com/tecnickcom/tc-lib-pdf-parser
* https://github.com/tecnickcom/tc-lib-pdf

Previously used in this library was **TCPDF**. But i removed it and moved some of its code to us (Ref: #299).

---

### About this fix

First of all, its great that you support us here, so please don't get me wrong. But i am not sure, if you know **why** your changes fix the issue. You wrote it yourself before: `Yes, this is more like a dirty fix.`. 

You added `\r\n` to include line breaks, which is Windows specific. Others like Linux use `\n` for instance. That leads to the question if your fix also covers PDFs which were generated on a Mac for instance?

To be honest, i still lack detailed knowledge about PDF parsing. So I can't decide if your fix works or not. Furthermore I just started to get used to the code of this library too. **That said I really would like to hear a third opinion on that change.**

This library is used by >600 projects (said Github) and they relying on us to keep it stable. If you can point me to some specification (or something like that) which supports the change you made, that would help.

Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: Hey @k00ni , i totally understand that. I am not expecting this to be merged without further review.

To my understanding the cross reference table is parsed just fine in TCPDF. 

_The byte offset in the decoded stream shall be a 10-digit number, padded with leading zeros if necessary,
giving the number of bytes from the beginning of the file to the beginning of the object._ 
(https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf)

but i did not find good resources if an object can be padded at that offset? which microsoft seems to be doing?
so i think a solution in `RawDataParser::getIndirectObject` might be the right choice. ("this is a dirty fix" was my understanding yesterday)

i referenced the tcpdf commit because it seems to address a similar issue. this was just fyi. and it does basically the same.

I dont get your point on the line breaks? i am removing both (CR & LF) which should work for windows and unix, am i wrong?

Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: fyi: Setasign/FPDI seems to do this for \x20\x0A\x0C\x0D\x09\x00

see PdfParser/Tokenizer.php

Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: or https://github.com/mozilla/pdf.js/blob/v2.5.207/src/core/obj.js#L1504

Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: as i understand https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDFReference13.pdf:

_PDF treats any sequence of consecutive white-space characters as if there were just one_

_For the most part, EOL markers are treated the same as any other white-space characters._

and **3.2.9 Indirect Objects** defines no special meaning for EOL.

**Comment by markus-lax** [comment]
Hi guys,

I guess I found a solution for the PDF-1.7 issue. For me it works perfect, so I hope it's useful and can be implemented. 

image

Regards,
Markus Lax

**Comment by k00ni** [comment]
Hi, is there a way to post the whole "fix", because on the picture some text parts are cut off.

**Comment by PaulBehrendtVentoro** [comment]
and it should be `if ( substr($pdfData, $offset, 1) === "\n" ) {`, which is basically the same i did, but without respecting carriage returns.

**Comment by PaulBehrendtVentoro** [comment]
btw. @k00ni: what ist the status on https://github.com/smalot/pdfparser/pull/312/files/e8b815790a9b7d7e4f502693466bce7d02d7fc68#r444900023

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 5]
```diff
@@ -470,8 +470,8 @@ protected function getIndirectObject($pdfData, $xref, $obj_ref, $offset = 0, $de
             throw new Exception('Invalid object reference for $obj.');
         }
         $objref = $obj[0].' '.$obj[1].' obj';
-        // ignore leading zeros
-        $offset += strspn($pdfData, '0', $offset);
+        // ignore newlines & leading zeros
+        $offset += strspn($pdfData, "0\r\n", $offset);
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:474]: In the link you posted they also check whitespaces. But here you only ignore newlines and leading zeros.

https://github.com/mozilla/pdf.js/blob/v2.5.207/src/core/obj.js#L1504

Comment (k00ni) [reply src/Smalot/PdfParser/RawData/RawDataParser.php:474]: And can you tell me, if there are any changes in future PDF versions related to this?

Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php]: added ignoring of whitespaces (see ISO 32000-1 > 7.2.2 Character Set > Table 1) which is revised version for PDF-1.7

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 6]
```diff
@@ -455,59 +455,69 @@ protected function decodeXrefStream($pdfData, $startxref, $xref = [])
...
+     * @param string $objRef   Object number and generation number separated by underscore character
      * @param int    $offset   Object offset
      * @param bool   $decoding If true decode streams
      *
      * @return array containing object data
      *
      * @throws Exception if invalid object reference found
      */
-    protected function getIndirectObject($pdfData, $xref, $obj_ref, $offset = 0, $decoding = true)
+    protected function getIndirectObject($pdfData, $xref, $objRef, $offset = 0, $decoding = true)
```
Comment (PaulBehrendtVentoro) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:466]: Pls double check my refactorings

Comment (k00ni) [reply src/Smalot/PdfParser/RawData/RawDataParser.php:466]: Looks good to me. I didn't found any `$obj_ref` anymore.

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 7]
```diff
@@ -455,59 +455,67 @@ protected function decodeXrefStream($pdfData, $startxref, $xref = [])
...
     {
-        $obj = explode('_', $obj_ref);
-        if (2 != \count($obj)) {
+        // --- build indirect object header
+        // $objHeader = "[object number] [generation number] obj"
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:469]: Please remove code which is commented out.

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 8]
```diff
@@ -455,59 +455,67 @@ protected function decodeXrefStream($pdfData, $startxref, $xref = [])
...
      * @return array containing object data
      *
      * @throws Exception if invalid object reference found
      */
-    protected function getIndirectObject($pdfData, $xref, $obj_ref, $offset = 0, $decoding = true)
+    protected function getIndirectObject($pdfData, $xref, $objRef, $offset = 0, $decoding = true)
     {
-        $obj = explode('_', $obj_ref);
-        if (2 != \count($obj)) {
+        // --- build indirect object header
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:468]: Just a small hint: I prefer separators like

```
/*
 * build indirect object header
 */
```
instead. The make it more clear that a new code section starts. 

But I wouldn't mind if you keep yours.

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 9]
```diff
@@ -455,59 +455,67 @@ protected function decodeXrefStream($pdfData, $startxref, $xref = [])
...
+        $objRefArr = explode('_', $objRef);
+        if (2 !== \count($objRefArr)) {
             throw new Exception('Invalid object reference for $obj.');
         }
-        $objref = $obj[0].' '.$obj[1].' obj';
-        // ignore leading zeros
+        $objHeader = $objRefArr[0].' '.$objRefArr[1].' obj';
+
+        // --- check if we are in position
+        // ignore whitespace characters at offset
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:477]: Please add all things you ignore there to the comment. As far as I can tell, you at least ignoring:

* tabs
* new lines
* whitespaces

File: src/Smalot/PdfParser/RawData/RawDataParser.php [hunk 10]
```diff
@@ -455,59 +455,67 @@ protected function decodeXrefStream($pdfData, $startxref, $xref = [])
...
-            $oldoffset = $offset;
+            $oldOffset = $offset;
             // get element
             $element = $this->getRawObject($pdfData, $offset);
             $offset = $element[2];
             // decode stream using stream's dictionary information
-            if ($decoding and ('stream' == $element[0]) and (isset($objdata[($i - 1)][0])) and ('<<' == $objdata[($i - 1)][0])) {
-                $element[3] = $this->decodeStream($pdfData, $xref, $objdata[($i - 1)][1], $element[1]);
+            if ($decoding && ('stream' === $element[0]) && (isset($objContentArr[($i - 1)][0])) && ('<<' === $objContentArr[($i - 1)][0])) {
+                $element[3] = $this->decodeStream($pdfData, $xref, $objContentArr[($i - 1)][1], $element[1]);
```
Comment (k00ni) [inline src/Smalot/PdfParser/RawData/RawDataParser.php:498]: Can you be sure that the `1` key is always set in `$objContentArr[($i - 1)][1]`? You only check for the `0` in the if-clause before.

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 7 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php:471]: this is more like pseudo code to know what is the result of the next few lines

File: src/Smalot/PdfParser/RawData/RawDataParser.php (hunk 10 above)
Comment (PaulBehrendtVentoro) [reply src/Smalot/PdfParser/RawData/RawDataParser.php:504]: i just replaced stuff that safely can be changed to get stuff all little bit more readable to me. I don't wanted to introduce breaking changes.
Adding another check could change behavior.

**Comment by k00ni** [comment]
Thank you.
