### PR TITLE
Baseencoding fallback

### LINKED ISSUE #665: Attempting to parse a PDF with a form field with two dots in it causes pdfparser to throw an exception
- PHP Version: 8.3.1
 - PDFParser Version: 2.7.0

### Description:
Attempting to parse a PDF with a form field with two dots in it causes pdfparser to throw an exception. Adobe Acrobat reads the PDF just fine as does `qpdf test.pdf --qdf test.qdf`.

### PDF input
[test.pdf](https://github.com/smalot/pdfparser/files/13881204/test.pdf)

### Expected output & actual output
The expected output is for it not to throw an exception. The actual output is an exception:

```
Fatal error: Uncaught Smalot\PdfParser\Exception\EncodingNotFoundException: Missing encoding data for: ""
```

### Code
```
<?php
require __DIR__ . '/vendor/autoload.php';

$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile('test.pdf');

$objects = $pdf->getObjects();
foreach ($objects as $obj) {
	print_r($obj->getDetails());
}
```

### PR DESCRIPTION
**Pull request by GreyWyvern**
When a document doesn't include a `BaseEncoding` header, `StandardEncoding` should be assumed as the default instead of an empty string.

# Type of pull request

* [X] Bug fix (involves code and configuration changes)

# About

Some documents which are short-and-sweet may not include a `BaseEncoding` header. In this case, the PDF Reference 1.7 describes this encoding as a default.

If the result of checking for the `BaseEncoding` returns an empty string, use `StandardEncoding` as the value instead. Resolves #665.

# Checklist for code / configuration changes

* [X] Please add at least **one test case** (unit test, system test, ...) to demonstrate that the change is working. If existing code was changed, your tests cover these code parts as well.
* [X] Please run **PHP-CS-Fixer** before committing, to confirm with our coding styles. See https://github.com/smalot/pdfparser/blob/master/.php-cs-fixer.php for more information about our coding styles.
* [X] In case you **fix an existing issue**, please do one of the following:
  * [X] Write in this text something like `fixes #1234` to outline that you are providing a fix for the issue `#1234`.

### CODE REVIEW

**Comment by GreyWyvern** [comment]
PHP CS Fixer is complaining about indentation in `Document.php`, `PDFObject.php` and `RawData\RawDataParser.php`. Files I didn't even modify. :( Running PHP CS Fixer on my local (Windows) machine doesn't find these issues either.

**Comment by k00ni** [comment]
I merged #670 into master which fixes these coding style issues.

File: src/Smalot/PdfParser/Encoding.php [hunk 1]
```diff
@@ -145,6 +145,12 @@ protected function getEncodingClass(): string
     {
         // Load reference table charset.
         $baseEncoding = preg_replace('/[^A-Z0-9]/is', '', $this->get('BaseEncoding')->getContent());
+
+        // Check for empty BaseEncoding field value
+        if ('' == $baseEncoding) {
```
Comment (k00ni) [inline src/Smalot/PdfParser/Encoding.php:150]: Based on https://www.php.net/manual/en/function.preg-replace.php, `preg_replace` can return `string`, `array` and `null`. Shouldn't we check for `[]` and `null` at this point too?

Comment (GreyWyvern) [reply src/Smalot/PdfParser/Encoding.php:150]: I could perhaps change the test to `if (empty($baseEncoding)) { ... }` ? How's that?

Comment (k00ni) [reply src/Smalot/PdfParser/Encoding.php:150]: I would change the whole part to:

```php
// Check for empty BaseEncoding field value
if (is_string($baseEncoding) && 0 < strlen($baseEncoding)) {
    $className = '\\Smalot\\PdfParser\\Encoding\\'.$baseEncoding;
} else {
    $baseEncoding = 'StandardEncoding';
}
```
Now we dont have to worry about null and empty arrays. I don't like `empty` personally, because it does too much magic and one may not be aware of its side "effects" (e.g. no warning if a variable doesn't exist). With this approach we are very explicit what we want and in all other cases we use `StandardEncoding`. 

However we do this code part, we must handle the null- and empty array case.

Comment (GreyWyvern) [reply src/Smalot/PdfParser/Encoding.php:150]: Since the `$className = ...` statement is right below this, it would be simpler to use:

```php
if (!is_string($baseEncoding) || 0 == strlen($baseEncoding)) {
  $baseEncoding = 'StandardEncoding';
}
```

Comment (k00ni) [reply src/Smalot/PdfParser/Encoding.php:150]: My bad, I forgot to adapt one line. In the following would be the whole function with my adaptions:

```php
protected function getEncodingClass(): string
{
    // Load reference table charset.
    $baseEncoding = preg_replace('/[^A-Z0-9]/is', '', $this->get('BaseEncoding')->getContent());

    // use base encoding class if a non-empty string is provided
    if (is_string($baseEncoding) && 0 < strlen($baseEncoding)) {
        $className = '\\Smalot\\PdfParser\\Encoding\\'.$baseEncoding;
    } else {
        $className = '\\Smalot\\PdfParser\\Encoding\\StandardEncoding';
    }

    if (!class_exists($className)) {
        throw new EncodingNotFoundException('Missing encoding data for: "'.$baseEncoding.'".');
    }

    return $className;
}
```

But your approach is fine too, mine was just a minor tweak. Feel free to use what you want.

File: src/Smalot/PdfParser/Encoding.php [hunk 2]
```diff
@@ -145,6 +145,12 @@ protected function getEncodingClass(): string
     {
         // Load reference table charset.
         $baseEncoding = preg_replace('/[^A-Z0-9]/is', '', $this->get('BaseEncoding')->getContent());
+
+        // Check for empty BaseEncoding field value
+        if (!\is_string($baseEncoding) || 0 == \strlen($baseEncoding)) {
```
Comment (k00ni) [inline src/Smalot/PdfParser/Encoding.php:150]: Just to make sure: if `$baseEncoding` is `null` or an `[ ]`, only the first part of the if-clauses is being used and the second part is not used, correct? The reason why I am asking, `strlen` triggers a warning or type error, if it receives a non-string as parameter.

Comment (GreyWyvern) [reply src/Smalot/PdfParser/Encoding.php:150]: Yes. If `!is_string()` is `true`, the second part of the expression isn't tested since it isn't needed. The only way the `strlen()` function is reached is if the first expression evaluated to `false` which means it *must* be a string.

**Review by k00ni — APPROVED** [review]

**Comment by k00ni** [comment]
Thank you!
